MapRules Integration
radiant-maxar/osm-tasking-manager2 pull request #1
Opened 2018-10-12 02:11 UTC by abalosc1

2018-10-12 15:43 UTC, maxgrossman requested changes
:clap: :clap: :clap: 

This is super cool, awesome stuff.
Less changing the url for opening editors this is ready for :ship:

2018-10-12 15:43 UTC, maxgrossman commented on osmtm/static/js/project.js
> +          var presets = map_rules_url + '/' + attribution_config_id + '/presets/iD'
per [#4](https://github.com/radiant-maxar/maprules/issues/4) we'll want these urls to be separate from the ones used to add the modal (one for the ui, other for the api)

2018-10-12 15:43 UTC, maxgrossman commented on osmtm/static/js/project.js
> +          var validations = map_rules_url + '/' + attribution_config_id + '/rules/iD'
so clean! so readable! so not how I do gross string concat :see_no_evil:

2018-10-12 20:15 UTC, maxgrossman approved these changes

2018-10-15 14:30 UTC, abalosc1 commented
Accidentally created this branch of master instead of develop

2018-10-15 14:30 UTC, closed without merging